version: '3'
services:
  sql:
    image: mysql:8.0.32
    container_name: conference_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=springboot
      - MYSQL_DATABASE=conference_db