version: '3'
services:
  database:
    image: mysql:8.0.32
    container_name: conference_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: conference_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass