spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conference
    username: root
    password: springboot
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      connection-url: jdbc:mysql://localhost:3306/conference
      dialect: org.hibernate.dialect.MySQLDialect